
services:
  backend:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    container_name: app_backend
    networks:
      - isolated_network
    ports:
      - "2222:2222"
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GROUP_ID}" 
    deploy:
      resources:
        limits:
          cpus: "2"           
          memory: "8G"        
        reservations:
          cpus: "1"           
          memory: "4G"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - isolated_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  isolated_network:
    driver: bridge
volumes:
  redis_data: